name: Build-Docker-Image

on: [push]

jobs: 
    build_docker_img:
     runs-on: ubuntu-latest
     env:
        TAG: java-api
        PAT: ${{ secrets.GITHUB_TOKEN}}
        USER: bhagya-cs
        REGISTRY: ghcr.io
        VERSION: v1

     steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Build Docker Image
          run: docker build -t $TAG

        - name: Login to gHCR
          run: |
           echo $PAT | docker login ghcr.io -u $USER --password-stdin
           docker tag $TAG ${{ env.REGISTRY }}/$User/$TAG:${{ env. VERSION }}
           docker push ${{ env.REGISTRY }}/$USER/$tag:${{ env.VERSION }}